/gps/particle neutron

/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/rot1 0 0 -1
/gps/pos/centre 250 0 0 cm
/gps/pos/halfx 250 cm
/gps/pos/halfy 250 cm

/gps/ang/type iso
/gps/ang/rot1 0 -1 0
/gps/ang/rot2 1 0 0
/gps/ang/minphi 0 deg
/gps/ang/maxphi 180 deg

/gps/ene/type Arb
/gps/ene/diffspec 1
/gps/hist/type arb

/control/getEnv NEUTRONHIST
#/control/echo {NEUTRONHIST}
/gps/hist/file {NEUTRONHIST}
/gps/hist/inter Lin
