/gps/particle neutron

/gps/pos/type Plane
/gps/pos/shape Rectangle
/gps/pos/rot1 1 0 0
/gps/pos/centre 0 0 250 cm
/gps/pos/halfx 250 cm
/gps/pos/halfy 250 cm

/gps/ang/type iso
/gps/ang/rot1 1 0 0
/gps/ang/rot2 0 1 0
/gps/ang/mintheta 0 deg
/gps/ang/maxtheta 90 deg

/gps/ene/type Arb
/gps/ene/diffspec 1
/gps/hist/type arb

/control/getEnv NEUTRONHIST
#/control/echo {NEUTRONHIST}
/gps/hist/file {NEUTRONHIST}
/gps/hist/inter Lin
